global:
  namespace: kbe-brewery-order-micro-service

service:
  type: NodePort

  port: 3306
  targetPort: 3306
  nodePort: 30306
  
  database: "beerservice"

  user: user
  password: dbpassword

  rootPassword: dbpassword

ingress:
  enabled: false

mysqlImage:
  repository: mysql
  tag: "9.6.0"
  pullPolicy: IfNotPresent
